name: Quality
on:
  push:
    paths:
      - "**/*.go"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "**/*.go"
      - ".github/workflows/**"
jobs:
  setup:
    name: Repo Setup
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - name: Check out code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        go mod download
    - name: Run Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.55
    - name: Run Unit tests
      run: |
        go test -race -coverpkg="./..." -covermode atomic -coverprofile=profile.cov ./...
    - name: Install goveralls
      run: go install github.com/mattn/goveralls@latest
    - name: Send coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.cov
