name: Quality
on:
  push:
    paths:
      - "**/*.go"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "**/*.go"
      - ".github/workflows/**"
jobs:
  setup:
    name: Repo Setup
    id: cache-npm
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - name: Check out code
      uses: actions/checkout@v4
    - name: Cache node modules
      uses: actions/cache@v3
      env:
        cache-name: cache-go-mod
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/go/pkg
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        go mod download -x
#    - name: Run Lint
#      uses: golangci/golangci-lint-action@v3
#      with:
#        version: v1.55
    - name: Run Unit tests
      run: |
        go test -race -coverpkg="./..." -covermode atomic -coverprofile=profile.cov ./...
    - name: Send coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.cov
